// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAukxFRLEDLGSdERHqK9xrYVn_M6jSYx9Q',
    appId: '1:361650070490:web:6a18bf9f7c7833790456e3',
    messagingSenderId: '361650070490',
    projectId: 'academia-201c2',
    authDomain: 'academia-201c2.firebaseapp.com',
    storageBucket: 'academia-201c2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNelx5rbaxR4EPuHjytQOLim9scaEvz-A',
    appId: '1:361650070490:android:d1e12b13b7480d8b0456e3',
    messagingSenderId: '361650070490',
    projectId: 'academia-201c2',
    storageBucket: 'academia-201c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNmIVPeN3NVgMSPD6Dq0AYjdcaC-otFCw',
    appId: '1:361650070490:ios:40a7006f5cec31da0456e3',
    messagingSenderId: '361650070490',
    projectId: 'academia-201c2',
    storageBucket: 'academia-201c2.firebasestorage.app',
    iosBundleId: 'com.dita.academia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNmIVPeN3NVgMSPD6Dq0AYjdcaC-otFCw',
    appId: '1:361650070490:ios:261e4d5d8b68b9050456e3',
    messagingSenderId: '361650070490',
    projectId: 'academia-201c2',
    storageBucket: 'academia-201c2.firebasestorage.app',
    iosBundleId: 'com.example.academia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAukxFRLEDLGSdERHqK9xrYVn_M6jSYx9Q',
    appId: '1:361650070490:web:0d04e2537613a0df0456e3',
    messagingSenderId: '361650070490',
    projectId: 'academia-201c2',
    authDomain: 'academia-201c2.firebaseapp.com',
    storageBucket: 'academia-201c2.firebasestorage.app',
  );
}
